In [1]:
import os
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.initializers import glorot_uniform
from tensorflow.keras.layers import Conv2D, Conv2DTranspose


In [8]:
input_shape = (1, 6, 8, 1)
x = tf.ones(input_shape)
l = Conv2D(1, 4, padding='same', kernel_initializer=tf.initializers.Ones(), use_bias=False)
y = l(x)

In [9]:
y2 = y.numpy().squeeze()
y2

array([[ 9., 12., 12., 12., 12., 12.,  9.,  6.],
       [12., 16., 16., 16., 16., 16., 12.,  8.],
       [12., 16., 16., 16., 16., 16., 12.,  8.],
       [12., 16., 16., 16., 16., 16., 12.,  8.],
       [ 9., 12., 12., 12., 12., 12.,  9.,  6.],
       [ 6.,  8.,  8.,  8.,  8.,  8.,  6.,  4.]], dtype=float32)

In [30]:
input_shape = (1, 3, 4, 1)
x = tf.ones(input_shape)
l = Conv2DTranspose(1, (2, 2), strides = 2, padding = 'valid', kernel_initializer=tf.initializers.Ones(), use_bias=False)
y = l(x)
l.set_weights([np.array([[[[1.]], [[2.]]], [[[3.]], [[4.]]]])])
y = l(x)

In [31]:
y2 = y.numpy().squeeze()
y2

array([[1., 2., 1., 2., 1., 2., 1., 2.],
       [3., 4., 3., 4., 3., 4., 3., 4.],
       [1., 2., 1., 2., 1., 2., 1., 2.],
       [3., 4., 3., 4., 3., 4., 3., 4.],
       [1., 2., 1., 2., 1., 2., 1., 2.],
       [3., 4., 3., 4., 3., 4., 3., 4.]], dtype=float32)

In [2]:
input_shape1 = (1, 6, 8, 3)
input_shape2 = (1, 6, 8, 1)
x1 = tf.ones(input_shape1)
x2 = tf.ones(input_shape2)
l = Conv2D(1, 4, padding='same', kernel_initializer=tf.initializers.Ones(), use_bias=False)
y1 = l(x1)

In [4]:
y1.numpy().squeeze()

array([[27., 36., 36., 36., 36., 36., 27., 18.],
       [36., 48., 48., 48., 48., 48., 36., 24.],
       [36., 48., 48., 48., 48., 48., 36., 24.],
       [36., 48., 48., 48., 48., 48., 36., 24.],
       [27., 36., 36., 36., 36., 36., 27., 18.],
       [18., 24., 24., 24., 24., 24., 18., 12.]], dtype=float32)

In [6]:
l.weights[0].shape

TensorShape([4, 4, 3, 1])

In [7]:
y2 = l(x2)
y2.numpy().squeeze()

ValueError: number of input channels does not match corresponding dimension of filter, 1 != 3